<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>llm_voice</name>
  <version>0.0.1</version>
  <description>LLM + ASR voice interaction node for ROS2</description>

  <maintainer email="lx_hmkk@qq.com">lx_hmkk</maintainer>
  <license>Apache-2.0</license>

  <!-- 依赖 -->
  <depend>rclpy</depend>
  <depend>std_msgs</depend>
  <depend>std_srvs</depend>
  <depend>arm_utils</depend>
  <exec_depend>arm_interfaces</exec_depend>
  <exec_depend>python3-yaml</exec_depend>

  <!-- 建议但非必须：让 rosdep 安装 Python3 解释器 -->
  <exec_depend>python3</exec_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
